stages:
  - unitTests
  - release
  - build_pub
  - compose_update

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master' # Execute jobs when a new commit is pushed to master branch
    - if: $CI_COMMIT_BRANCH == 'dev' # Execute jobs when a new commit is pushed to dev branch

variables:
  COMPOSE_SERVER: $COMPOSE_SERVER_IP
  COMPOSE_SERVER_USER: $COMPOSE_SERVER_USER

unitTests:
  image: node:14
  stage: unitTests
  script:
    - cd client
    - npm i
    - CI=true npm test --passWithNoTests
  only:
    - master
    - dev

release:
  except:
    - schedules
  image: node:14
  stage: release
  script:
    - npm i
    - npx semantic-release
  only:
    - master
    - dev

build_pub:
  except:
    - schedules
  image: docker:20-git
  stage: build_pub
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_REPO: przemr/fibservice
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
    - docker build -t $IMAGE_REPO:fib-client ./client
    - docker build -t $IMAGE_REPO:fib-nginx ./nginx
    - docker build -t $IMAGE_REPO:fib-server ./server
    - docker build -t $IMAGE_REPO:fib-worker ./worker
    - docker push $IMAGE_REPO:fib-client
    - docker push $IMAGE_REPO:fib-nginx
    - docker push $IMAGE_REPO:fib-server
    - docker push $IMAGE_REPO:fib-worker
  only:
    - master

.ssh-connect-tpe: &ssh-connect
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - ssh-keyscan ${COMPOSE_SERVER} > ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add -

.ssh-compose-update-tpe: &ssh-compose-update
  - ssh ${COMPOSE_SERVER_USER}@${COMPOSE_SERVER} "cd ~/docker; echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin; docker compose -f $COMPOSE_FILE down; docker compose -f $COMPOSE_FILE pull && docker compose -f $COMPOSE_FILE up -d"

.compose-update-settings-tpe: &compose-update-settings
  except:
    - schedules
  image: docker:20-git
  stage: compose_update
  services:
    - docker:19.03.12-dind
  before_script:
    - *ssh-connect
  script:
    - *ssh-compose-update

compose_publish:
  variables:
    COMPOSE_FILE: docker-compose.yml
  <<: *compose-update-settings
  only:
    - master
