stages:
  - installDependencies
  - unitTest
  - release
  # - build_dev
  # - build_pub
  # - compose_update

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master' # Execute jobs when a new commit is pushed to master branch
    - if: $CI_COMMIT_BRANCH == 'dev' # Execute jobs when a new commit is pushed to dev branch

# to cache both npm modules we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - node_modules

# this job installs NPM dependencies
installDependencies:
  image: node:14
  stage: installDependencies
  script:
    - npm i
  only:
    - master
    - dev

unitTest:
  image: node:14
  stage: unitTest
  script:
    - echo "Testing App"
    - cd client
    - npm i
    - CI=true npm test --passWithNoTests
    - echo "Test successfully!"
  only:
    - master
    - dev

release:
  except:
    - schedules
  image: node:14
  stage: release
  script:
    - npm i
    - npx semantic-release
  only:
    - master
    - dev
